#!/bin/sh

if [ `whoami` = "jenkins" ]
then
    SSH_IDENTITY=~/.ssh/id_rsa
else
    SSH_IDENTITY=~/.ssh/virginia.pem
fi

mkdir bin

echo "Building client with go"
go build -o bin/client client/client.go

if [ $? -ne 0 ]
then
    echo "Client build failed, exiting"
    exit 1   
fi

echo "Building server with go"
go build -o bin/server server/server.go

if [ $? -ne 0 ]
then
    echo "Server build failed, exiting"
    exit 1   
fi

echo "Performing unit test"
python script/clienttest.py
if [ $? -ne 0 ]
then
    echo "IRC Server unit test failed, exiting"
    exit 1   
fi

# Deployment
ssh -i $SSH_IDENTITY ubuntu@ec2-54-227-84-172.compute-1.amazonaws.com "killall -9 go"

scp -i $SSH_IDENTITY server/server.go ubuntu@ec2-54-227-84-172.compute-1.amazonaws.com:
if [ $? -ne 0 ]
then
    echo "Server deploy failed, exiting"
    exit 1   
fi

ssh -i $SSH_IDENTITY ubuntu@ec2-54-227-84-172.compute-1.amazonaws.com "go run server.go -d &"

if [ $? -ne 0 ]
then
    echo "SSH of server to test box failed, exiting"
    exit 1
fi

python script/clienttest.py ec2-54-227-84-172.compute-1.amazonaws.com
if [ $? -ne 0 ]
then
    echo "IRC Server system test failed, exiting"
    exit 1   
fi

echo "Deployment completed successfully"

exit 0
